// lib/constants/shipmentStatus.js

export const SHIPMENT_STATUSES = {
  LABEL_CREATED: "LABEL_CREATED",

  PICKED_UP: "PICKED_UP",

  AT_ORIGIN_HUB: "AT_ORIGIN_HUB",

  EXPORT_CUSTOMS_PENDING:
    "EXPORT_CUSTOMS_PENDING",

  EXPORT_CUSTOMS_CLEARED:
    "EXPORT_CUSTOMS_CLEARED",

  INTERNATIONAL_TRANSIT:
    "INTERNATIONAL_TRANSIT",

  ARRIVED_DESTINATION_COUNTRY:
    "ARRIVED_DESTINATION_COUNTRY",

  IMPORT_CUSTOMS_PENDING:
    "IMPORT_CUSTOMS_PENDING",

  IMPORT_CUSTOMS_CLEARED:
    "IMPORT_CUSTOMS_CLEARED",

  AT_DESTINATION_HUB:
    "AT_DESTINATION_HUB",

  OUT_FOR_DELIVERY:
    "OUT_FOR_DELIVERY",

  DELIVERED: "DELIVERED",

  DELIVERY_FAILED:
    "DELIVERY_FAILED",

  RETURN_TO_SENDER:
    "RETURN_TO_SENDER",

  EXCEPTION: "EXCEPTION"
};