// lib/logistics/statusMachine.js

import { SHIPMENT_STATUSES } from "../constants/shipmentStatus";

export const ALLOWED_TRANSITIONS = {
  [SHIPMENT_STATUSES.LABEL_CREATED]: [
    SHIPMENT_STATUSES.PICKED_UP
  ],

  [SHIPMENT_STATUSES.PICKED_UP]: [
    SHIPMENT_STATUSES.AT_ORIGIN_HUB
  ],

  [SHIPMENT_STATUSES.AT_ORIGIN_HUB]: [
    SHIPMENT_STATUSES.EXPORT_CUSTOMS_PENDING
  ],

  [SHIPMENT_STATUSES.EXPORT_CUSTOMS_PENDING]: [
    SHIPMENT_STATUSES.EXPORT_CUSTOMS_CLEARED
  ],

  [SHIPMENT_STATUSES.EXPORT_CUSTOMS_CLEARED]: [
    SHIPMENT_STATUSES.INTERNATIONAL_TRANSIT
  ],

  [SHIPMENT_STATUSES.INTERNATIONAL_TRANSIT]: [
    SHIPMENT_STATUSES.ARRIVED_DESTINATION_COUNTRY
  ],

  [SHIPMENT_STATUSES.ARRIVED_DESTINATION_COUNTRY]: [
    SHIPMENT_STATUSES.IMPORT_CUSTOMS_PENDING
  ],

  [SHIPMENT_STATUSES.IMPORT_CUSTOMS_PENDING]: [
    SHIPMENT_STATUSES.IMPORT_CUSTOMS_CLEARED
  ],

  [SHIPMENT_STATUSES.IMPORT_CUSTOMS_CLEARED]: [
    SHIPMENT_STATUSES.AT_DESTINATION_HUB
  ],

  [SHIPMENT_STATUSES.AT_DESTINATION_HUB]: [
    SHIPMENT_STATUSES.OUT_FOR_DELIVERY
  ],

  [SHIPMENT_STATUSES.OUT_FOR_DELIVERY]: [
    SHIPMENT_STATUSES.DELIVERED
  ],

  [SHIPMENT_STATUSES.DELIVERED]: []
};